CREATED help README file to add missing details
redhat-cop/openshift-templates pull request #51
Opened 2019-09-01 19:04 UTC by bryantson

Running the Template file needs the additional information about how to get the required arguments

#### What is this PR About?
Describe the contents of the PR

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/day-in-the-life

2019-09-02 00:05 UTC, pabrahamsson requested changes
Thank you @bryantson 
A few comments, I like the idea of documenting the template parameters. Typically I'd use the `description` field of the parameter for this.
If we want to use a README I think it should include all the template parameters (including the optional).
Maybe use a [table](https://www.markdownguide.org/extended-syntax/#tables) to describe the parameters, required/optional, default values and description.

2019-09-02 00:05 UTC, pabrahamsson commented on prometheus/README.md
> +- More description are needed
Either delete this line or put something more descriptive here.

2019-09-27 16:29 UTC, pabrahamsson commented
@bryantson will you be able to update this PR?

2019-10-09 03:19 UTC, bryantson commented
@pabrahamsson Sorry. I just read this. Sure.

2019-11-08 15:51 UTC, garethahealy commented
@bryantson ; if you are going to duplicate the content from the template into the readme, can you try to use some type of tool which can copy/process the yaml into the readme?

I am thinking of something like:
- https://github.com/zakhenry/embedme

It's mainly to stop the readme and template going out of sync.

@pabrahamsson ; thoughts?

2019-11-11 03:48 UTC, pabrahamsson commented
@garethahealy not sure using embedme would be suitable here. I think all we're looking for is to document the template parameters (which again can be done in the `description` field of the template). My understanding is that embedme would include the whole template file, correct?
@bryantson will you be able to follow up with your intentions here? Are you looking to create a README or are you ok with updating the `description` filed of the parameters?

2019-11-11 10:32 UTC, garethahealy commented
@pabrahamsson just to clarify. i agree with you that the "source of truth" for the parameters should be the template file and not something else. so if this PR is just to add more detail to the descriptions, then the embedme point can be ignored.

however, if @bryantson was going to include the params in the readme (which it seems hes started to do), then i think it would be a good idea to look into using a tool which could automate that. embedme was an example, which can select a line number range from a file and insert it into an md file. its probably not the final answer, as am sure there are tools which could process the yaml template and convert the params to an md-table which would be nicer.

does that make sense?

2019-11-11 15:22 UTC, pabrahamsson commented
Thank you for the clarification @garethahealy, I had missed the line number range option which certainly makes this tool quite useful. I think you and I are both on the same page here and at this point I'd like to hear from @bryantson and what his thoughts are.

2019-11-14 17:12 UTC, bryantson commented
Need to get back to you. I need to try this to ensure what to recommend.

2020-06-29 14:58 UTC, garethahealy commented
@bryantson ; any update on this? just to see if we can progress it/get it merged.

2021-03-29 14:04 UTC, garethahealy commented
closing due to inactivity

2021-03-29 14:04 UTC, closed without merging