Add initial operatorhub templates
redhat-cop/openshift-templates pull request #64
Opened 2019-11-01 15:17 UTC by tylerauerbeck

#### What is this PR About?
This adds some initial templates for interacting with OperatorHub. This assumes that OLM is running and configured appropriately.

#### How do we test this?

Test by deploying the Elasticsearch operator on OCP 4:

```
oc new-project my-namespace

oc process -f operatorgroup.yaml -p NAME=openshift-logging-operatorgroup -p TARGET_NAMESPACE=my-namespace| oc apply -f - -n my-namespace

oc process -f catalogsourceconfig.yml -p NAME=elasticsearch-operator -p OPERATORS="elasticsearch-operator" | oc apply -f - -n openshift-marketplace

oc process -f subscription.yaml -p NAME=elasticsearch-operator -p OPERATOR_NAME=elasticsearch-operator -p OPERATOR_NAMESPACE=openshift-operators -p CATALOG_SOURCE_NAME=elasticsearch-operator | oc apply -f - -n openshift-operators
```

cc: @redhat-cop/day-in-the-life

2019-11-04 15:15 UTC, pabrahamsson requested changes
Looks good @tylerauerbeck, two minor comments inline.

2019-11-04 15:15 UTC, pabrahamsson commented on operatorhub/subscription.yml
> +    namespace: "${OPERATOR_NAMESPACE}"
I think this line should be removed and instead set the namespace from cli or from the applier.

2019-11-04 15:15 UTC, pabrahamsson commented on operatorhub/README.md
> +- [Subscription](subscription.yml)
Since the order matter here, can you make it an ordered list?

2019-11-08 14:56 UTC, tylerauerbeck commented
@pabrahamsson Fixed. Let me know what you think.

2019-11-08 15:01 UTC, pabrahamsson approved these changes
LGTM

2019-11-08 15:02 UTC, merged